export interface BookmarkNode {
  /** Unique id generated by our app */
  id: string;
  /** Display title for folder or bookmark */
  title: string;
  /** URL for bookmarks, empty for folders */
  url?: string;
  /** Icon URL (favicon) */
  icon?: string;
  /** Optional description / note */
  description?: string;
  /** Children for folders */
  children?: BookmarkNode[];
  /** true for folders */
  isFolder: boolean;
}

export type ThemeMode = 'day' | 'night';

export interface SearchEngines {
  google: string;
  bing: string;
  baidu: string;
}

/** A node rendered as a single card item (leaf bookmark) */
export interface FlatBookmark extends BookmarkNode {
  /** Path of folder titles from root to this bookmark */
  path: string[];
}
